apiVersion: apps/v1
kind: Deployment
metadata:
  name: randexample-client
  labels:
    app: randexample-client
    role: client
spec:
  selector:
    matchLabels:
      app: randexample-client
      role: client
  replicas: 10
  template:
    metadata:
      labels:
        app: randexample-client
        role: client
    spec:
      containers:
      - image: caccola/randexample:latest
        name: client
        env:
        - name: ADDRESS
          value: 'randomnumber:50051'
        args:
        - 'client'
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "250m"
