---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: randomnumber-route
spec:
  hosts:
  - randomnumber.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: randomnumber.default.svc.cluster.local
        subset: prod
      weight: 0
    - destination:
        host: randomnumber.default.svc.cluster.local
        subset: canary
      weight: 100

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: randomnumber-destination
  namespace: default
spec:
  host: randomnumber.default.svc.cluster.local
  subsets:
  - name: prod
    labels:
      version: prod
  - name: canary
    labels:
      version: canary
